name: "Conventional Changelog Reader"
description: "Read and parse the CHANGELOG file of the project"
branding:
  icon: "circle"
  color: "purple"
inputs:
  path:
    description: "Path to the CHANGELOG file containing the log entries"
    required: false
    default: "./CHANGELOG.md"
  version:
    description: "Version of the log entry wanted"
    required: false
outputs:
  version:
    description: "Version of the log entry found"
  date:
    description: "Release date of the log entry found"
  status:
    description: "Status of the log entry found. Possibly one of the following: prereleased, released, unreleased, or yanked"
  changes:
    description: "Description text of the log entry found"
runs:
  using: "node12"
  main: "dist/index.js"
